/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pungo.andongo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author helvi
 */
public class QuantidadeDeVisitasPorAnimal extends javax.swing.JFrame {

    /**
     * Creates new form QuantidadeDeVisitasPorAnimal
     */
    public QuantidadeDeVisitasPorAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jEscolha = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        lblTipoVisita = new javax.swing.JLabel();
        jTipoVisita = new javax.swing.JComboBox<>();
        jCodAnimal = new javax.swing.JTextField();
        jDataV = new javax.swing.JTextField();
        lblCodAnimal = new javax.swing.JLabel();
        lblDataV = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jNomeV = new javax.swing.JTextField();
        lblNomeV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quantidade de Visitas por Animal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quantidade de Visitas Por Animal");

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Tipo de Visita", "Descrição", "Custo", "Animal", "Data da Visita"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabela);

        jEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Visita", "Nome e Data das Vacinas", "Quantidade de Consultas Realizadas", "Quantidade de Vezes que o Animal Realizou a Higiente" }));
        jEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolhaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo Listagem");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Contador:");

        lblContador.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblContador.setText("0");

        lblTipoVisita.setText("Tipo de Visita");

        jTipoVisita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulta", "Vacina", "Higiene" }));

        jCodAnimal.setText("clixao");

        lblCodAnimal.setText("Cod do Animal");

        lblDataV.setText("Data da Vacina");

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblNomeV.setText("Nome da Vacina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEscolha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTipoVisita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataV))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(263, 263, 263)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContador))
                            .addComponent(lblTipoVisita)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jNomeV, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDataV, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCodAnimal))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCodAnimal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblContador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoVisita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTipoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataV)
                    .addComponent(lblNomeV))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomeV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lblCodAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCodAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Item Selecionado
        String itemSelecionado = (String) jEscolha.getSelectedItem();
        if(itemSelecionado.equals("Tipo de Visita"))
        {
            lblCodAnimal.setVisible(false);
            lblNomeV.setVisible(false);
            lblDataV.setVisible(false);
            jNomeV.setVisible(false);
            jCodAnimal.setVisible(false);
            jDataV.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolhaActionPerformed
        // TODO add your handling code here:
        //Item Selecionado
        String itemSelecionado = (String) jEscolha.getSelectedItem();
        if(itemSelecionado.equals("Tipo de Visita"))
        {
            lblCodAnimal.setVisible(false);
            lblDataV.setVisible(false);
            lblNomeV.setVisible(false);
            jNomeV.setVisible(false);
            jCodAnimal.setVisible(false);
            jDataV.setVisible(false);
            //Caso clique novamente
            lblTipoVisita.setVisible(true);
            jTipoVisita.setVisible(true);
        }
        
        else if(itemSelecionado.equals("Nome e Data das Vacinas"))
        {
            lblTipoVisita.setVisible(false);
            lblCodAnimal.setVisible(false);
            jTipoVisita.setVisible(false);
            jCodAnimal.setVisible(false);
            //Desabilita as outras
            lblNomeV.setVisible(true);
            jNomeV.setVisible(true);
            lblDataV.setVisible(true);
            jDataV.setVisible(true);
            //Caso Clique novamente
        }
        
        else if(itemSelecionado.equals("Quantidade de Consultas Realizadas"))
        {
            lblCodAnimal.setVisible(true);
            jCodAnimal.setVisible(true);
            //Desabilitando as outras
            lblTipoVisita.setVisible(false);
            jTipoVisita.setVisible(false);
            lblNomeV.setVisible(false);
            lblDataV.setVisible(false);
            jNomeV.setVisible(false);
            jDataV.setVisible(false);
            //Clicando novamente
            jCodAnimal.setVisible(true);
        }
        
        else
        {
            lblCodAnimal.setVisible(true);
            jCodAnimal.setVisible(true);
            //Desabilitando as outras
            lblTipoVisita.setVisible(false);
            jTipoVisita.setVisible(false);
            lblNomeV.setVisible(false);
            lblDataV.setVisible(false);
            jNomeV.setVisible(false);
            jDataV.setVisible(false);
            //Clicando novamente
            jCodAnimal.setVisible(true);
        }
    }//GEN-LAST:event_jEscolhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu_Visitas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Modelo
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        //Resetando linhas
        modelo.setRowCount(0);
        String itemSelecionado = (String) jEscolha.getSelectedItem();
        
        if(itemSelecionado.equals("Tipo de Visita"))
        {
            String tipoVisita = (String) jTipoVisita.getSelectedItem();
             //Inserindo valores
             setValoresTabela(modelo, new Visitas().ListagemDeVisitasPorTipo(tipoVisita)); 
        }
        
        else if(itemSelecionado.equals("Nome e Data das Vacinas"))
        {
            String nomeV = jNomeV.getText();
            String dataV = jDataV.getText();
            //Inserindo Valores
            setValoresTabela(modelo, new Visitas().ListagemVacinaPorNomeData(nomeV, dataV));
        }
      
        else if(itemSelecionado.equals("Quantidade de Consultas Realizadas"))
        {
            String codAnimal = jCodAnimal.getText();
            //Inserindo valores
             setValoresTabela(modelo, new Visitas().ListagemDeConsultasRealizadasPorAnimal(codAnimal));
        }
        else if(itemSelecionado.equals("Quantidade de Vezes que o Animal Realizou a Higiente"))
        {
            String codAnimal = jCodAnimal.getText();
            //Inserindo valores
             setValoresTabela(modelo, new Visitas().ListagemDeHigieneRealizadasPorAnimal(codAnimal));
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    //Inserindo valores na tabela
    private void setValoresTabela(DefaultTableModel modelo, ArrayList<String[]>lista)
    {
        try
        {
            for(String[] linha:lista)
           {
            modelo.addRow(new Object[]{linha[0],linha[1],linha[2], linha[3],linha[4],linha[5]});
           }
            
            int qtdLinhas = modelo.getRowCount();
            String linhas = Integer.toString(qtdLinhas);
            lblContador.setText(linhas);
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null,"A lista encontra-se vazia.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuantidadeDeVisitasPorAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuantidadeDeVisitasPorAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuantidadeDeVisitasPorAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuantidadeDeVisitasPorAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuantidadeDeVisitasPorAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCodAnimal;
    private javax.swing.JTextField jDataV;
    private javax.swing.JComboBox<String> jEscolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNomeV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JComboBox<String> jTipoVisita;
    private javax.swing.JLabel lblCodAnimal;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblDataV;
    private javax.swing.JLabel lblNomeV;
    private javax.swing.JLabel lblTipoVisita;
    // End of variables declaration//GEN-END:variables
}
